#!/usr/bin/env python3
"""
Pre-compute similarity scores for all crops and save to disk.

Reads grid.bin + reference farm coordinates, computes MAX dot-product similarity
for each layer, and writes binary score files to data/scores_<crop>.bin.

Usage:
    python scripts/precompute_crops.py [--layer coffee] [--grid data/grid.bin]

Each output file format:
    [4 bytes]  width: uint32
    [4 bytes]  height: uint32
    [4 bytes]  pin_count: uint32
    [4 bytes]  reserved: uint32
    [width*height*4 bytes]  scores: float32[] (row-major, 0.0-1.0)
    [width*height bytes]    best_pin: uint8[] (index of best-matching pin)
    [pin_count*64 bytes]    ref_embeddings: int8[] (for COG refinement)
"""

import json
import struct
import time
import sys
import os
import numpy as np
from pathlib import Path

# Reference farm coordinates per crop (must match frontend/src/utils/referenceFarms.ts)
LAYERS = {
    "avocado": [
        (36.7823, -4.0512), (36.7845, -4.0892),
        (-0.7234, 37.1523), (-0.4512, 37.2345),
        (34.3972, -119.4911), (33.32, -116.99),
        (5.7706, -75.7681), (5.7823, -75.7234), (5.6234, -75.6912), (5.5703, -75.4028),
        (-23.7845, 30.2134), (-23.0456, 30.3123), (-25.0234, 31.1678),
        (19.3208, -101.6803), (19.35, -102.3667), (19.8608, -103.5939),
        (-8.1, -78.95), (-14.08, -75.7019),
        (-32.9167, -71.2136), (-32.2558, -70.9275),
        (32.9494, 35.1072),
        (14.6667, -90.6458),
        (18.5506, -70.4942),
        (-9.3261, 34.7814),
    ],
    "coffee": [
        (6.1234, 38.2156), (6.1567, 38.1923), (6.4234, 38.8123), (5.7823, 38.8912), (9.2845, 42.1534),
        (1.8234, -76.0412), (1.7912, -75.8534), (1.8678, -76.0823), (2.4012, -75.8456), (1.4123, -77.1234),
        (14.5678, -90.7512), (15.3456, -91.5023), (8.7945, -82.4678), (14.6234, -91.1523),
        (-0.3823, 36.9823), (-0.4678, 37.3012), (-1.1234, 36.8012), (-0.4912, 37.4523), (-0.7234, 37.0823),
        (4.6512, 96.8234), (2.5678, 98.9012), (-2.9823, 119.8234), (-8.0678, 114.2012), (-8.2234, 115.3678),
    ],
    "wine-grapes": [
        (45.1864, -0.7517), (45.0412, -0.6678), (45.1634, -0.7823), (47.1623, 4.9512),
        (41.1423, -7.5234), (38.3812, -7.5823), (41.1734, -7.4512), (41.1234, -7.5012), (41.8234, -8.3923),
        (43.2412, 10.6234), (43.4823, 11.2345), (43.0234, 11.4678), (44.5923, 7.9923), (44.7219, 8.0733),
        (-34.5834, 139.0234), (-35.2008, 138.5433), (-33.8234, 138.6034),
        (-33.4523, -69.2734), (-39.025, -67.6614), (-33.0289, -68.9581), (-33.4734, -69.1823), (-33.5823, -69.0923),
    ],
    "cacao": [
        (-1.5623, -79.7012), (-0.8234, -80.1678),
        (19.1923, -69.8734),
        (6.9234, -73.1234),
        (-13.6523, 48.4234),
        (-5.0823, -80.1234), (-6.5123, -76.3234), (-3.5923, -80.4234), (-12.8923, -72.7012),
    ],
    "macadamia": [
        (-24.8444, 152.3611), (-24.9612, 152.3012), (-25.2234, 152.2834), (-28.8511, 153.4553),
        (19.4923, -155.9012), (20.0823, -155.4678), (20.0634, -155.4234),
        (-36.834167, 175.774722),
        (-0.5012, 37.4823), (-0.4623, 37.2123), (-0.8012, 37.0234),
        (25.0823, 99.2234), (22.821111, 101.040833), (22.0412, 100.7923),
    ],
    "sugarcane": [
        (-22.4262, -48.6563), (-22.739, -49.9611), (-10.1136, -36.108), (-17.7277, -49.4139),
        (27.2811, 77.1027), (28.7732, 79.4562), (27.3356, 78.3106), (16.9848, 74.4748),
        (16.9848, 101.9385), (15.0311, 102.7316), (15.4956, 102.5271),
        (29.9149, -91.731), (26.9217, -80.5857),
        (3.8133, -76.3138),
        (14.1648, -90.9295), (13.9945, -90.7059),
        (-28.9265, 31.4745),
        (-26.4266, -64.5382),
        (30.5689, 72.0511), (30.5913, 72.6514),
        (-7.6087, 112.2271),
    ],
}

EMPIRICAL_MAX = 105000.0
BANDS = 64


def load_layer_references(path):
    """Load crop references from JSON file (generated by generate_layer_references.py)."""
    with open(path) as f:
        data = json.load(f)
    crops = {}
    for crop_id, crop_def in data.items():
        farms = [(f["lat"], f["lng"]) for f in crop_def["pins"]]
        crops[crop_id] = farms
    return crops


def load_grid(path):
    """Load grid.bin header and data."""
    with open(path, "rb") as f:
        magic = f.read(8)
        assert magic == b"TRGRID01", f"Bad magic: {magic}"
        version = struct.unpack("<I", f.read(4))[0]
        bands = struct.unpack("<I", f.read(4))[0]
        width = struct.unpack("<I", f.read(4))[0]
        height = struct.unpack("<I", f.read(4))[0]
        west, south, east, north = struct.unpack("<4d", f.read(32))
        scales = np.frombuffer(f.read(256), dtype=np.float32).copy()
        offsets = np.frombuffer(f.read(256), dtype=np.float32).copy()

        total = width * height
        data = np.frombuffer(f.read(total * bands), dtype=np.int8).reshape(height, width, bands)

        import math
        mask_bytes = math.ceil(total / 8)
        mask_raw = np.frombuffer(f.read(mask_bytes), dtype=np.uint8)
        land_mask = np.unpackbits(mask_raw, bitorder="big")[:total].reshape(height, width).astype(bool)

    cell_w = (east - west) / width
    cell_h = (north - south) / height

    return {
        "width": width, "height": height,
        "west": west, "south": south, "east": east, "north": north,
        "cell_w": cell_w, "cell_h": cell_h,
        "data": data, "land_mask": land_mask,
        "scales": scales, "offsets": offsets,
    }


def latlng_to_rowcol(grid, lat, lng):
    col = int((lng - grid["west"]) / grid["cell_w"])
    row = int((grid["north"] - lat) / grid["cell_h"])
    col = max(0, min(col, grid["width"] - 1))
    row = max(0, min(row, grid["height"] - 1))
    return row, col


def compute_crop(grid, farms):
    """Compute MAX similarity scores for a set of reference farms."""
    w, h = grid["width"], grid["height"]
    total = w * h

    # Look up reference embeddings
    ref_embeddings = []
    for lat, lng in farms:
        row, col = latlng_to_rowcol(grid, lat, lng)
        if grid["land_mask"][row, col]:
            emb = grid["data"][row, col, :].copy()
            ref_embeddings.append(emb)

    if not ref_embeddings:
        return None, None, None

    refs = np.array(ref_embeddings, dtype=np.int32)  # (N, 64)
    n_refs = len(refs)
    print(f"    {n_refs}/{len(farms)} valid reference embeddings")

    # Get land pixel indices
    land_rows, land_cols = np.where(grid["land_mask"])
    n_land = len(land_rows)
    print(f"    {n_land} land pixels to process")

    # Compute in chunks to manage memory
    scores = np.zeros(total, dtype=np.float32)
    best_pin = np.zeros(total, dtype=np.uint8)

    chunk_size = 1_000_000
    for start in range(0, n_land, chunk_size):
        end = min(start + chunk_size, n_land)
        rows = land_rows[start:end]
        cols = land_cols[start:end]

        pixels = grid["data"][rows, cols, :].astype(np.int32)  # (chunk, 64)
        dots = pixels @ refs.T  # (chunk, N)

        max_idx = dots.argmax(axis=1)
        max_dots = dots[np.arange(len(dots)), max_idx]

        pixel_indices = rows * w + cols
        scores[pixel_indices] = np.clip(max_dots / EMPIRICAL_MAX, 0.0, 1.0)
        best_pin[pixel_indices] = max_idx.astype(np.uint8)

        if (start // chunk_size) % 5 == 0:
            pct = end / n_land * 100
            print(f"    {pct:.0f}% ({end}/{n_land})")

    return scores, best_pin, np.array(ref_embeddings, dtype=np.int8)


def save_scores(path, width, height, scores, best_pin, ref_embeddings):
    """Write scores file."""
    pin_count = len(ref_embeddings)
    with open(path, "wb") as f:
        f.write(struct.pack("<IIII", width, height, pin_count, 0))
        f.write(scores.tobytes())
        f.write(best_pin.tobytes())
        f.write(ref_embeddings.tobytes())

    size_mb = os.path.getsize(path) / 1024 / 1024
    print(f"    Saved: {path} ({size_mb:.1f} MB)")


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--grid", default="data/grid.bin")
    parser.add_argument("--layer", help="Only compute this crop (default: all)")
    parser.add_argument("--output-dir", default="data")
    parser.add_argument("--refs", default="data/layer_references.json",
                        help="JSON file with crop references (from generate_layer_references.py)")
    args = parser.parse_args()

    print("Loading grid...")
    t0 = time.time()
    grid = load_grid(args.grid)
    print(f"Grid loaded: {grid['width']}x{grid['height']} in {time.time()-t0:.1f}s")

    # Load crops from JSON if it exists, merge with hardcoded LAYERS
    all_crops = dict(LAYERS)
    if os.path.exists(args.refs):
        json_crops = load_layer_references(args.refs)
        print(f"Loaded {len(json_crops)} crops from {args.refs}")
        all_crops.update(json_crops)
    else:
        print(f"No {args.refs} found, using hardcoded crops only")

    crops_to_compute = all_crops
    if args.layer:
        if args.layer not in all_crops:
            print(f"Unknown crop: {args.layer}. Available: {list(all_crops.keys())}")
            sys.exit(1)
        crops_to_compute = {args.layer: all_crops[args.layer]}

    os.makedirs(args.output_dir, exist_ok=True)

    for crop_id, farms in crops_to_compute.items():
        print(f"\n{'='*50}")
        print(f"Computing: {crop_id} ({len(farms)} farms)")
        print(f"{'='*50}")

        t1 = time.time()
        scores, best_pin, ref_emb = compute_crop(grid, farms)

        if scores is None:
            print(f"  SKIPPED: no valid embeddings")
            continue

        elapsed = time.time() - t1
        land_scores = scores[scores > 0]
        print(f"    Computed in {elapsed:.1f}s")
        print(f"    Score stats: p50={np.median(land_scores):.3f} p90={np.percentile(land_scores, 90):.3f} p99={np.percentile(land_scores, 99):.3f} max={land_scores.max():.3f}")

        out_path = os.path.join(args.output_dir, f"scores_{crop_id}.bin")
        save_scores(out_path, grid["width"], grid["height"], scores, best_pin, ref_emb)

    print(f"\nAll done! Total time: {time.time()-t0:.0f}s")


if __name__ == "__main__":
    main()
